# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-29 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_publish',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u53d1\u5e03\u65f6\u95f4'),
        ),
    ]
